export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const GET_SEARCHED_PRODUCTS = "GET_SEARCHED_PRODUCTS";
export const GET_SEARCHED_PRODUCTS_SUCCESS = "GET_SEARCHED_PRODUCTS_SUCCESS";

export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";

export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";

export const GET_PRODUCT_CATALOG = "GET_PRODUCT_CATALOG";
export const GET_PRODUCT_CATALOG_SUCCESS = "GET_PRODUCT_CATALOG_SUCCESS";

export const EDIT_PRODUCT_CATALOG = "EDIT_PRODUCT_CATALOG";
export const EDIT_PRODUCT_CATALOG_SUCCESS = "EDIT_PRODUCT_CATALOG_SUCCESS";

export const UPDATE_PRODUCT_CATALOG = "UPDATE_PRODUCT_CATALOG";
export const UPDATE_PRODUCT_CATALOG_SUCCESS = "UPDATE_PRODUCT_CATALOG_SUCCESS";

export const ADD_PRODUCT_CATALOG = "ADD_PRODUCT_CATALOG";
export const ADD_PRODUCT_CATALOG_SUCCESS = "ADD_PRODUCT_CATALOG_SUCCESS";
